import {createChart,CandlestickSeries,HistogramSeries,LineSeries,createSeriesMarkers} from 'https://cdn.jsdelivr.net/npm/lightweight-charts@5.0.8/+esm';

const $=id=>document.getElementById(id);
let chart,indicator,candleSeries,volumeSeries,currentMode='BACKTEST',paperPoll=null;
const palette=['#58a6ff','#f2cc60','#3fb950','#ff7b72','#bc8cff','#39c5cf','#ff9f43','#7bed9f'];
function sec(ms){return Math.floor(ms/1000)}
function n(v,d=2){if(v===null||v===undefined||Number.isNaN(Number(v)))return '-';return Number(v).toFixed(d)}
function setStatus(x){$('status').textContent=x}
function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function initCharts(){chart=createChart($('chart'),{autoSize:true,layout:{background:{color:'#0b0e11'},textColor:'#b8c4d1'},grid:{vertLines:{color:'#18202a'},horzLines:{color:'#18202a'}},crosshair:{mode:0},timeScale:{timeVisible:true,secondsVisible:false}});candleSeries=chart.addSeries(CandlestickSeries,{upColor:'#2ecc71',downColor:'#ff5c5c',borderVisible:false,wickUpColor:'#2ecc71',wickDownColor:'#ff5c5c'});volumeSeries=chart.addSeries(HistogramSeries,{priceFormat:{type:'volume'},priceScaleId:'vol',lastValueVisible:false,priceLineVisible:false});chart.priceScale('vol').applyOptions({scaleMargins:{top:.82,bottom:0}});indicator=createChart($('indicator'),{autoSize:true,layout:{background:{color:'#0b0e11'},textColor:'#8795a6'},grid:{vertLines:{color:'#18202a'},horzLines:{color:'#18202a'}},timeScale:{visible:false}});chart.timeScale().subscribeVisibleLogicalRangeChange(r=>{if(r)indicator.timeScale().setVisibleLogicalRange(r)});}
function resetDynamic(){chart?.remove();indicator?.remove();$('chart').innerHTML='';$('indicator').innerHTML='';initCharts()}
function optionList(items,includeNone=false){return `${includeNone?'<option value="">(none)</option>':''}${items.map(s=>`<option>${esc(s)}</option>`).join('')}`}
async function loadConfig(){const c=await fetch('/api/config').then(r=>r.json());$('strategy').innerHTML=optionList(c.strategies);$('confirm1').innerHTML=optionList(c.strategies,true);$('confirm2').innerHTML=optionList(c.strategies,true);$('confirmationPolicy').innerHTML=c.confirmation_policies.map(x=>`<option>${esc(x)}</option>`).join('');$('strategy').value='Supertrend';$('confirmationPolicy').value='Single';try{const s=await fetch('/api/symbols').then(r=>r.json());$('symbol').innerHTML=s.symbols.map(x=>`<option>${esc(x)}</option>`).join('');$('symbol').value=c.default_symbol}catch{$('symbol').innerHTML='<option>ETH/USDT:USDT</option><option>BTC/USDT:USDT</option><option>DOGE/USDT:USDT</option>'}syncConfirmationControls()}
function syncConfirmationControls(){const single=$('confirmationPolicy').value==='Single';$('confirm1').disabled=single;$('confirm2').disabled=single;$('confirmationRequired').disabled=single||$('confirmationPolicy').value!=='Quorum Recent Events';$('confirmationWindow').disabled=single||$('confirmationPolicy').value==='Primary + All States'}
function requestPayload(){const nullable=id=>$(id).value?Number($(id).value):null;let manual=null;const raw=$('manualParams').value.trim();if(raw)manual=JSON.parse(raw);const confirmations=[$('confirm1').value,$('confirm2').value].filter(Boolean).filter(x=>x!==$('strategy').value);return{symbol:$('symbol').value,timeframe:$('timeframe').value,strategy:$('strategy').value,confirmations,confirmation_policy:$('confirmationPolicy').value,confirmation_required:Number($('confirmationRequired').value),confirmation_window_bars:Number($('confirmationWindow').value),limit:Number($('bars').value),starting_balance:Number($('balance').value),leverage:Number($('leverage').value),allocation_pct:Number($('allocation').value),pyramiding:Number($('pyramiding').value),direction:$('direction').value,entry_fee_pct:Number($('entryFee').value),exit_fee_pct:Number($('exitFee').value),extra_cost_pct:Number($('extraCost').value),desired_net_profit_pct:Number($('netTarget').value),referral_share_pct:Number($('referral').value),maintenance_margin_pct:Number($('maintenance').value),max_bars_in_trade:nullable('maxBars'),stop_loss_pct:nullable('stopLoss'),funding_bps_per_8h:0,manual_params:manual}}
function receiptSummary(r){if(!Array.isArray(r)||!r.length)return 'single';return r.map(x=>`${x.matched?'✓':'×'} ${x.strategy}${x.age_bars===null||x.age_bars===undefined?'':` (${x.age_bars}b)`}`).join(' · ')}
function draw(data){resetDynamic();candleSeries.setData(data.candles.map(c=>({time:sec(c.ts_ms),open:c.open,high:c.high,low:c.low,close:c.close})));volumeSeries.setData(data.candles.map(c=>({time:sec(c.ts_ms),value:c.volume,color:c.close>=c.open?'rgba(46,204,113,.35)':'rgba(255,92,92,.35)'})));let k=0;for(const [name,pts] of Object.entries(data.overlays||{})){const s=chart.addSeries(LineSeries,{color:palette[k++%palette.length],lineWidth:2,title:name,priceLineVisible:false,lastValueVisible:false});s.setData(pts.map(p=>({time:sec(p.ts_ms),value:p.value})))}let j=0;for(const [name,pts] of Object.entries(data.panes||{})){const s=indicator.addSeries(LineSeries,{color:palette[j++%palette.length],lineWidth:2,title:name,priceLineVisible:false,lastValueVisible:true});s.setData(pts.map(p=>({time:sec(p.ts_ms),value:p.value})))}const markers=(data.markers||[]).map(m=>({time:sec(m.ts_ms),position:m.kind==='entry'?(m.side==='long'?'belowBar':'aboveBar'):(m.side==='long'?'aboveBar':'belowBar'),color:m.kind==='entry'?(m.side==='long'?'#2ecc71':'#ff5c5c'):'#f2cc60',shape:m.kind==='entry'?(m.side==='long'?'arrowUp':'arrowDown'):'circle',text:m.text})).sort((a,b)=>a.time-b.time);createSeriesMarkers(candleSeries,markers);const p=data.open_position;if(p){candleSeries.createPriceLine({price:p.avg_entry,color:'#58a6ff',title:'Avg Entry'});candleSeries.createPriceLine({price:p.break_even,color:'#f39c12',title:'Break-even'});candleSeries.createPriceLine({price:p.profit_target,color:'#2ecc71',title:'Profit Target'});candleSeries.createPriceLine({price:p.liquidation,color:'#ff5c5c',title:'Liquidation ~'});}chart.timeScale().fitContent();render(data)}
function render(d){const m=d.metrics;const cls=v=>Number(v)>=0?'positive':'negative';const model=d.entry_model||{label:d.strategy,policy:'Single',window_bars:1};$('tester').innerHTML=`<div class="metrics">${[['Net P&L',m.total_equity_pnl],['Open P&L',m.open_pnl],['Profit factor',m.profit_factor],['Win rate %',m.win_rate_pct],['Max DD %',m.max_drawdown_pct],['Target hit %',m.target_hit_rate_pct],['Median bars',m.median_bars_to_exit],['Fees paid',m.fees_paid],['Referral',m.referral_revenue],['Trades/day',m.trades_per_day],['Revenue/day',m.referral_revenue_per_day],['Closed trades',m.closed_trades]].map(([a,b])=>`<div class="metric"><span class="muted">${a}</span><b class="${a.includes('P&L')?cls(b):''}">${n(b,a.includes('%')?2:4)}</b></div>`).join('')}</div><p><b>Entry model:</b> ${esc(model.label)} · ${esc(model.policy)} · window ${model.window_bars} bar(s)</p><p class="muted">Presets: ${esc(JSON.stringify(d.params))}</p>`;$('tradeRows').innerHTML=d.trades.slice().reverse().map(t=>`<tr><td>${t.trade}</td><td>${esc(t.side)}</td><td title="${esc(receiptSummary(t.entry_confirmation))}">${esc(receiptSummary(t.entry_confirmation))}</td><td>${t.layers}</td><td>${n(t.entry_price)}</td><td>${n(t.exit_price)}</td><td class="${cls(t.net_pnl)}">${n(t.net_pnl,4)}</td><td>${n(t.entry_fee,4)}</td><td>${n(t.exit_fee,4)}</td><td>${n(t.total_fee,4)}</td><td>${n(t.referral_commission,4)}</td><td>${n(t.leverage,0)}x</td><td>${n(t.margin,2)}</td><td>${n(t.mae_pct,3)}%</td><td>${n(t.mfe_pct,3)}%</td><td>${t.bars_held}</td><td>${esc(t.exit_reason)}</td></tr>`).join('');$('economics').innerHTML=`<div class="metrics"><div class="metric">Trader fees<b>${n(m.fees_paid,4)}</b></div><div class="metric">Referrer payout<b>${n(m.referral_revenue,4)}</b></div><div class="metric">Trades/day<b>${n(m.trades_per_day,2)}</b></div><div class="metric">Referral/day<b>${n(m.referral_revenue_per_day,4)}</b></div></div>`;const p=d.open_position;$('openPosition').innerHTML=p?`<b>OPEN ${esc(p.side.toUpperCase())}</b><br>Layers ${p.layers}<br>Avg ${n(p.avg_entry)}<br>Break-even ${n(p.break_even)}<br>Target ${n(p.profit_target)}<br><span class="negative">Liquidation ~ ${n(p.liquidation)}</span><br>Open P&L ${n(p.open_pnl,4)}<br>Used margin ${n(p.used_margin,4)}<br>Free collateral ${n(p.free_collateral,4)}<br>MAE ${n(p.mae_pct,3)}%<br>Bars ${p.bars_held}<br><small>${esc(receiptSummary(p.entry_confirmation))}</small>`:'No open position';}
async function runBacktest(){setStatus('Running sequential composite backtest against HTX candles…');$('run').disabled=true;try{const payload=requestPayload();const r=await fetch('/api/backtest',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Backtest failed');draw(d);setStatus(`Done: ${d.entry_model.label} ${d.symbol} ${d.timeframe} · ${d.metrics.closed_trades} closed trades`)}catch(e){setStatus(`Error: ${e.message}`)}finally{$('run').disabled=false}}
async function pollPaper(){try{const d=await fetch('/api/paper-live/status').then(r=>r.json());$('paperStart').disabled=currentMode!=='PAPER'||d.running;$('paperStop').disabled=currentMode!=='PAPER'||!d.running;const p=d.position;const sig=d.last_signal;const model=d.entry_model;$('paperState').innerHTML=`<b>${d.running?'RUNNING':'STOPPED'}</b>${model?`<br>${esc(model.primary)} · ${esc(model.policy)}`:''}<br>Last closed bar: ${d.last_bar_ts_ms?new Date(d.last_bar_ts_ms).toLocaleString():'-'}${sig?`<br>Last signal: ${esc(sig.side)} · ${esc(receiptSummary(sig.receipt))}`:''}${p?`<br>Position: ${esc(p.side)} ${n(p.qty,6)} @ ${n(p.entry_price)}<br>Layers: ${d.layers}`:'<br>Position: flat'}${d.last_error?`<br><span class="negative">${esc(d.last_error)}</span>`:''}`;$('paperEventRows').innerHTML=(d.events||[]).slice().reverse().map(e=>`<tr><td>${new Date(e.ts_ms).toLocaleTimeString()}</td><td>${esc(e.kind)}</td><td>${esc(e.detail)}</td></tr>`).join('')}catch(e){$('paperState').textContent=`Paper status error: ${e.message}`}}
async function startPaper(){try{setStatus('Starting fail-closed PAPER runner through epinnox-online…');const r=await fetch('/api/paper-live/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(requestPayload())});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Paper start failed');setStatus('PAPER runner started. epinnox-online must remain on an active paper profile.');await pollPaper()}catch(e){setStatus(`PAPER start error: ${e.message}`)}}
async function stopPaper(){try{await fetch('/api/paper-live/stop',{method:'POST'});setStatus('PAPER runner stopped. Existing paper positions were not force-closed.');await pollPaper()}catch(e){setStatus(`PAPER stop error: ${e.message}`)}}
function setMode(mode){currentMode=mode;document.querySelectorAll('.mode').forEach(x=>x.classList.toggle('active',x.dataset.mode===mode));$('paperStart').disabled=mode!=='PAPER';$('paperStop').disabled=mode!=='PAPER';if(mode==='BACKTEST')setStatus('Backtest mode ready.');else if(mode==='PAPER'){setStatus('Paper mode: live HTX candles + epinnox-online paper execution.');pollPaper()}else setStatus('LIVE is not armed. Use epinnox-online directly until the live adapter receives a separate qualification pass.')}
$('run').addEventListener('click',runBacktest);$('paperStart').addEventListener('click',startPaper);$('paperStop').addEventListener('click',stopPaper);$('confirmationPolicy').addEventListener('change',syncConfirmationControls);document.querySelectorAll('.tabbar button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tabbar button').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab').forEach(x=>x.classList.add('hidden'));b.classList.add('active');$(b.dataset.tab).classList.remove('hidden')}));document.querySelectorAll('.mode').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));
initCharts();await loadConfig();await runBacktest();paperPoll=setInterval(()=>{if(currentMode==='PAPER')pollPaper()},2000);
