(()=>{
  'use strict';
  if(window.__EPINNOX_PRODUCT_CHROME__)return;
  window.__EPINNOX_PRODUCT_CHROME__=true;

  const $=id=>document.getElementById(id);
  const WATCH=[['BTC/USDT:USDT','BTC'],['ETH/USDT:USDT','ETH'],['SOL/USDT:USDT','SOL'],['XRP/USDT:USDT','XRP']];
  const NAV=[
    ['Terminal','/','Market workspace','⌁'],
    ['Scanner','/scanner','Live opportunity discovery','⌘'],
    ['Universe','/?universe=1','Market intelligence','⌬'],
    ['Sessions','/sessions','Paper operations','▣'],
    ['Research','/research','Evidence library','◇'],
    ['Strategies','/strategies','Models & presets','◈'],
  ];
  const cache=new Map();let marketTimer=null,sessionTimer=null,clockTimer=null,symbols=null;
  const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const code=s=>String(s||'').split('/')[0].replace(/[^A-Z0-9]/gi,'').toUpperCase()||'—';
  const fmt=(v,d=2)=>Number.isFinite(Number(v))?Number(v).toLocaleString(undefined,{minimumFractionDigits:d,maximumFractionDigits:d}):'—';
  const page=()=>location.pathname.startsWith('/scanner')?'Scanner':location.pathname.startsWith('/sessions')?'Sessions':location.pathname.startsWith('/research')?'Research':location.pathname.startsWith('/strategies')?'Strategies':new URLSearchParams(location.search).has('universe')?'Universe':'Terminal';

  function assetIcon(symbol){const c=code(symbol);if(c==='BTC')return '<span class="pc-asset-icon xs btc">₿</span>';if(c==='ETH')return '<span class="pc-asset-icon xs eth">◆</span>';if(c==='SOL')return '<span class="pc-asset-icon xs sol"><i></i><i></i><i></i></span>';return `<span class="pc-asset-icon xs generic">${esc(c.slice(0,2))}</span>`}
  async function market(symbol){const hit=cache.get(symbol);if(hit&&Date.now()-hit.at<12000)return hit.data;const r=await fetch(`/api/market?symbol=${encodeURIComponent(symbol)}&timeframe=1m&limit=64`);const d=await r.json();if(!r.ok)throw new Error(d.detail||'market unavailable');cache.set(symbol,{at:Date.now(),data:d});return d}
  function setSymbol(symbol){let w={schema_version:1,saved_at_ms:Date.now(),mode:'BACKTEST',values:{}};try{const old=JSON.parse(localStorage.getItem('epinnox.workspace.v1')||'null');if(old?.schema_version===1)w=old}catch{}w.saved_at_ms=Date.now();w.values={...(w.values||{}),symbol};localStorage.setItem('epinnox.workspace.v1',JSON.stringify(w));location.href='/'}

  function installHeader(){const h=document.querySelector('.product-header');if(!h)return;h.classList.add('pc-header');const health=h.querySelector('.product-health');if(health){health.id='pcTickerDeck';health.className='pc-ticker-deck';health.innerHTML=WATCH.map(([symbol,c])=>`<button class="pc-ticker" type="button" data-symbol="${symbol}" title="Open ${c}">${assetIcon(symbol)}<span class="pc-ticker-id"><b>${c}</b></span><span class="pc-ticker-quote"><strong data-price>—</strong><em data-change>—</em></span></button>`).join('');health.querySelectorAll('[data-symbol]').forEach(b=>b.addEventListener('click',()=>setSymbol(b.dataset.symbol)))}const mode=h.querySelector('.product-mode');if(mode){mode.id='pcTopTools';mode.className='pc-top-tools';mode.innerHTML='<div class="pc-search"><span>⌕</span><input id="pcSymbolSearch" type="search" autocomplete="off" placeholder="Search symbol…" aria-label="Search symbol"><div id="pcSearchResults" class="pc-popover pc-search-results hidden"></div></div><button id="pcAlerts" class="pc-icon-button" type="button" title="System status">◌<i></i></button><button id="pcSettings" class="pc-icon-button" type="button" title="Strategy configuration">⚙</button><button id="pcProfile" class="pc-profile" type="button"><span>E</span><b>Epinnox<em><i></i> Connected</em></b></button><div id="pcSystemPopover" class="pc-popover pc-system hidden"></div>';$('pcSymbolSearch')?.addEventListener('input',search);$('pcAlerts')?.addEventListener('click',e=>{e.stopPropagation();system()});$('pcSettings')?.addEventListener('click',()=>location.href='/?open=strategy');$('pcProfile')?.addEventListener('click',e=>{e.stopPropagation();profile()});document.addEventListener('click',e=>{if(!e.target.closest?.('#pcTopTools'))closePopovers()})}}

  function installSidebar(){const side=document.querySelector('.product-sidebar');if(!side)return;let nav=side.querySelector('.product-nav');if(!nav){nav=document.createElement('nav');nav.className='product-nav';side.prepend(nav)}const active=page();nav.innerHTML=NAV.map(([name,href,desc,icon])=>`<a href="${href}" class="${name===active?'active':''}" data-page="${name}"><span class="nav-icon pc-nav-icon">${icon}</span><span class="nav-copy"><strong>${name.toUpperCase()}</strong><span>${desc}</span></span></a>`).join('');let label=side.querySelector('.nav-label');if(!label){label=document.createElement('div');label.className='nav-label';side.insertBefore(label,nav)}label.textContent='COMMAND CENTER';side.querySelectorAll('.sidebar-status,.pc-session-block,.pc-side-art').forEach(x=>x.remove());const sessions=document.createElement('section');sessions.className='pc-session-block';sessions.innerHTML='<div class="pc-side-label"><span>PAPER SESSIONS</span><b id="pcSessionCount">0</b></div><div id="pcSessionMini" class="pc-session-mini"><span>Loading runtime…</span></div><a class="pc-new-session" href="/?mode=PAPER">＋ New Session</a>';side.appendChild(sessions);const art=document.createElement('div');art.className='pc-side-art';art.innerHTML='<div></div><span>DISCIPLINE<br>BUILDS FREEDOM</span>';side.appendChild(art)}

  function installFooter(){const shell=document.querySelector('.product-shell');if(!shell||$('pcFooter'))return;const f=document.createElement('footer');f.id='pcFooter';f.className='pc-footer';f.innerHTML=`<div class="pc-footer-clock"><i></i><b id="pcClock">--:--:--</b><span>${page()}</span></div><div id="pcFooterTape" class="pc-footer-tape"></div><div class="pc-footer-cues"><span>◇ Evidence First</span><span>★ No Assumptions</span><span>Serve Benjamin ↗</span></div>`;shell.appendChild(f);tick();clockTimer=setInterval(tick,1000)}
  function tick(){if($('pcClock'))$('pcClock').textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'})}

  async function refreshMarket(){if(document.hidden)return;await Promise.allSettled(WATCH.map(async([symbol,c])=>{const d=await market(symbol),cl=(d.candles||[]).map(x=>Number(x[4])).filter(Number.isFinite);if(cl.length<2)return;const last=cl.at(-1),chg=cl[0]?((last/cl[0])-1)*100:0;const card=document.querySelector(`.pc-ticker[data-symbol="${CSS.escape(symbol)}"]`);if(!card)return;card.querySelector('[data-price]').textContent=fmt(last,last>=100?2:4);const e=card.querySelector('[data-change]');e.textContent=`${chg>=0?'+':''}${fmt(chg,2)}%`;e.classList.toggle('negative',chg<0)}));const tape=$('pcFooterTape');if(tape)tape.innerHTML=WATCH.map(([,c])=>{const e=[...document.querySelectorAll('.pc-ticker')].find(x=>x.dataset.symbol.startsWith(`${c}/`))?.querySelector('[data-change]')?.textContent||'—';return `<span>${c} <b class="${e.startsWith('-')?'negative':''}">${esc(e)}</b></span>`}).join('')}

  async function refreshSessions(){try{const r=await fetch('/api/sessions?limit=20'),d=await r.json(),active=(d.sessions||[]).filter(x=>['RUNNING','RECOVERED','RECONCILING','RECOVERY_REQUIRED'].includes(String(x.status)));if($('pcSessionCount'))$('pcSessionCount').textContent=String(active.length);const box=$('pcSessionMini');if(box)box.innerHTML=active.length?active.slice(0,4).map((s,i)=>`<a href="/sessions" class="pc-session-row" data-state="${esc(s.status)}"><i></i><span><b>P-${String(i+1).padStart(2,'0')} · ${esc(code(s.symbol||s.request?.symbol))}</b><em>${esc(s.strategy||s.request?.strategy||'—')}</em></span><strong>${esc(String(s.status).replaceAll('_',' '))}</strong></a>`).join(''):'<span>No active paper sessions.</span>'}catch{if($('pcSessionMini'))$('pcSessionMini').innerHTML='<span>Runtime unavailable.</span>'}}

  async function loadSymbols(){if(symbols)return symbols;try{const d=await fetch('/api/symbols').then(r=>r.json());symbols=Array.isArray(d.symbols)?d.symbols:[]}catch{symbols=WATCH.map(x=>x[0])}return symbols}
  async function search(){const box=$('pcSearchResults'),q=($('pcSymbolSearch')?.value||'').trim().toLowerCase();if(!box)return;if(!q){box.classList.add('hidden');return}const rows=(await loadSymbols()).filter(s=>String(s).toLowerCase().includes(q)||code(s).toLowerCase().includes(q)).slice(0,9);box.innerHTML=rows.length?rows.map(s=>`<button type="button" data-symbol="${esc(s)}">${assetIcon(s)}<span><b>${esc(code(s))}</b><em>${esc(s)}</em></span></button>`).join(''):'<span class="pc-search-empty">No matching symbol</span>';box.classList.remove('hidden');box.querySelectorAll('[data-symbol]').forEach(b=>b.addEventListener('click',()=>setSymbol(b.dataset.symbol)))}
  function closePopovers(){$('pcSearchResults')?.classList.add('hidden');$('pcSystemPopover')?.classList.add('hidden')}
  async function system(){const box=$('pcSystemPopover');if(!box)return;box.classList.remove('hidden');box.innerHTML='<div class="pc-pop-head">SYSTEM STATUS</div><div class="pc-system-note">Checking runtime…</div>';try{const s=await fetch('/api/live/status').then(r=>r.json());box.innerHTML=`<div class="pc-pop-head">SYSTEM STATUS</div><div class="pc-system-row"><span>Universe</span><b>${esc(s.universe?.state||'—')}</b></div><div class="pc-system-row"><span>Scanner</span><b>${esc(s.scanner?.state||'—')}</b></div><div class="pc-system-row"><span>Cycle</span><b>${esc(s.scanner?.cycle??'—')}</b></div>`}catch{box.innerHTML='<div class="pc-pop-head">SYSTEM STATUS</div><div class="pc-system-note">Runtime status unavailable.</div>'}}
  function profile(){const box=$('pcSystemPopover');if(!box)return;box.classList.remove('hidden');box.innerHTML=`<div class="pc-pop-head">EPINNOX</div><div class="pc-system-row"><span>Surface</span><b>${esc(page())}</b></div><div class="pc-system-row"><span>Intelligence</span><b>Serving Benjamin</b></div>`}

  function boot(){installHeader();installSidebar();installFooter();refreshMarket();refreshSessions();marketTimer=setInterval(refreshMarket,15000);sessionTimer=setInterval(()=>{if(!document.hidden)refreshSessions()},5000);document.addEventListener('visibilitychange',()=>{if(!document.hidden){refreshMarket();refreshSessions()}});window.addEventListener('beforeunload',()=>{clearInterval(marketTimer);clearInterval(sessionTimer);clearInterval(clockTimer)})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();