(()=>{
  'use strict';
  if(window.__EPINNOX_CANONICAL_SHELL__)return;
  window.__EPINNOX_CANONICAL_SHELL__=true;
  const $=id=>document.getElementById(id);
  const WATCH=[['BTC/USDT:USDT','BTC'],['ETH/USDT:USDT','ETH'],['SOL/USDT:USDT','SOL'],['XRP/USDT:USDT','XRP']];
  const NAV=[['Terminal','/','Market workspace','⌁'],['Scanner','/scanner','Live opportunity discovery','⌘'],['Universe','/?universe=1','Market intelligence','⌬'],['Sessions','/sessions','Paper operations','▣'],['Research','/research','Evidence library','◇'],['Strategies','/strategies','Models & presets','◈']];
  const ACTIVE_SESSION_STATES=new Set(['RUNNING','RECOVERED','RECONCILING','RECOVERY_REQUIRED']);
  const cache=new Map();let symbols=null,marketTimer=null,sessionTimer=null,clockTimer=null;
  const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const code=s=>String(s||'').split('/')[0].replace(/[^A-Z0-9]/gi,'').toUpperCase()||'—';
  const fmt=(v,d=2)=>Number.isFinite(Number(v))?Number(v).toLocaleString(undefined,{minimumFractionDigits:d,maximumFractionDigits:d}):'—';
  const closeOf=c=>Number(Array.isArray(c)?c[4]:c?.close);
  const isChart=()=>!!document.querySelector('.app-shell');
  const page=()=>location.pathname.startsWith('/scanner')?'Scanner':location.pathname.startsWith('/sessions')?'Sessions':location.pathname.startsWith('/research')?'Research':location.pathname.startsWith('/strategies')?'Strategies':new URLSearchParams(location.search).has('universe')?'Universe':'Terminal';
  function assetIcon(symbol){const c=code(symbol);if(c==='BTC')return '<span class="pc-asset-icon xs btc">₿</span>';if(c==='ETH')return '<span class="pc-asset-icon xs eth">◆</span>';if(c==='SOL')return '<span class="pc-asset-icon xs sol"><i></i><i></i><i></i></span>';return `<span class="pc-asset-icon xs generic">${esc(c.slice(0,2))}</span>`}
  function selectedSymbol(){if(isChart())return $('symbol')?.value||'ETH/USDT:USDT';try{return JSON.parse(localStorage.getItem('epinnox.workspace.v1')||'null')?.values?.symbol||'ETH/USDT:USDT'}catch{return'ETH/USDT:USDT'}}
  function setSymbol(symbol){if(isChart()&&$('symbol')){$('symbol').value=symbol;$('symbol').dispatchEvent(new Event('change',{bubbles:true}));return}let w={schema_version:1,saved_at_ms:Date.now(),mode:'BACKTEST',values:{}};try{const old=JSON.parse(localStorage.getItem('epinnox.workspace.v1')||'null');if(old?.schema_version===1)w=old}catch{}w.saved_at_ms=Date.now();w.values={...(w.values||{}),symbol};localStorage.setItem('epinnox.workspace.v1',JSON.stringify(w));location.href='/'}
  async function market(symbol){const hit=cache.get(symbol);if(hit&&Date.now()-hit.at<12000)return hit.data;const r=await fetch(`/api/market?symbol=${encodeURIComponent(symbol)}&timeframe=1m&limit=100`);const d=await r.json();if(!r.ok)throw new Error(d.detail||'market unavailable');cache.set(symbol,{at:Date.now(),data:d});return d}
  function modeMarkup(){return '<div class="ep-global-modes" aria-label="Operating mode"><button class="mode active" data-mode="BACKTEST"><span class="mode-dot"></span>Backtest</button><button class="mode" data-mode="PAPER"><span class="mode-dot"></span>Paper</button><button class="mode mode-unarmed" data-mode="LIVE" title="Live mode is visible but unarmed · real order routing stays closed"><span class="mode-dot"></span>Live<span class="mode-lock">UNARMED</span></button></div>'}
  function buildHeader(){const old=document.querySelector(isChart()?'.topbar':'.product-header');if(!old)return;const existingModes=isChart()?old.querySelector('.modes'):null;const h=document.createElement('header');h.id='epGlobalHeader';h.className='ep-global-header';h.innerHTML=`<a class="ep-brand" href="/"><img src="/static/assets/epinnox-mark.webp" alt="Epinnox"><span><strong>EPINNOX TERMINAL</strong><em>Capital intelligence · Serving Benjamin</em></span></a><div id="epTickerDeck" class="ep-ticker-deck">${WATCH.map(([s,c])=>`<button class="ep-ticker" type="button" data-symbol="${s}" title="Open ${c}">${assetIcon(s)}<span><b>${c}</b><strong data-price>—</strong><em data-change>—</em></span></button>`).join('')}</div><div class="ep-global-tools"><div class="ep-search"><span>⌕</span><input id="epSymbolSearch" type="search" autocomplete="off" placeholder="Search symbol…"><div id="epSearchResults" class="ep-popover hidden"></div></div><button id="epSystem" class="ep-icon" type="button" title="System status">◌<i id="epSystemLed"></i></button><button id="epSettings" class="ep-icon" type="button" title="Strategy settings">⚙</button><div id="epModeHost"></div><div id="epSystemPopover" class="ep-popover ep-system hidden"></div></div>`;old.replaceWith(h);const host=$('epModeHost');if(existingModes){existingModes.className='ep-global-modes';host.appendChild(existingModes);const live=existingModes.querySelector('[data-mode="LIVE"]');if(live){live.classList.add('mode-unarmed');live.title='Live mode is visible but unarmed · real order routing stays closed';if(!live.querySelector('.mode-lock'))live.insertAdjacentHTML('beforeend','<span class="mode-lock">UNARMED</span>')}}else{host.innerHTML=modeMarkup();host.querySelectorAll('.mode').forEach(b=>b.addEventListener('click',()=>location.href=`/?mode=${encodeURIComponent(b.dataset.mode)}`))}h.querySelectorAll('[data-symbol]').forEach(b=>b.addEventListener('click',()=>setSymbol(b.dataset.symbol)));$('epSymbolSearch')?.addEventListener('input',renderSearch);$('epSystem')?.addEventListener('click',e=>{e.stopPropagation();showSystem()});$('epSettings')?.addEventListener('click',()=>{if(isChart()&&window.EpinnoxV5Chart?.openStrategyModal){window.EpinnoxV5Chart.openStrategyModal();return}location.href='/?open=strategy'});document.addEventListener('click',e=>{if(!e.target.closest?.('.ep-global-tools'))closePopovers()})}
  function navMarkup(active){return NAV.map(([name,href,desc,icon])=>`<a href="${href}" data-page="${name}" class="ep-nav-item ${name===active?'active':''}" title="${name}"><span class="ep-nav-icon">${icon}</span><span class="ep-nav-copy"><strong>${name}</strong><em>${desc}</em></span></a>`).join('')}
  function buildSidebar(){const old=document.querySelector(isChart()?'#sessionRail':'.product-sidebar');if(!old)return;const universeController=isChart()?old.querySelector('#railUniverse'):null;const side=document.createElement('aside');side.id='epGlobalNav';side.className='ep-global-nav';side.setAttribute('aria-label','Epinnox command center');side.innerHTML=`<div class="ep-nav-title">COMMAND CENTER</div><nav class="ep-primary-nav rail-primary">${navMarkup(page())}</nav><section class="ep-session-block"><div class="ep-session-head"><span>PAPER SESSIONS</span><b id="epSessionCount">0</b></div><div id="epSessionList" class="ep-session-list"><span>Loading runtime…</span></div><a class="ep-new-session" href="/?mode=PAPER">＋ New Session</a></section><div class="ep-nav-spacer"></div><div class="ep-nav-art"><span>DISCIPLINE<br>BUILDS FREEDOM</span></div>`;if(universeController){universeController.hidden=true;universeController.classList.add('ep-internal-controller');side.appendChild(universeController)}old.replaceWith(side);side.querySelectorAll('.ep-primary-nav a').forEach(a=>a.addEventListener('click',e=>{if(isChart()&&a.dataset.page==='Universe'){e.preventDefault();const open=()=>{const btn=$('railUniverse');if(btn){btn.click();setActiveNav('Universe');setPageLabel('Universe');document.dispatchEvent(new Event('epinnox:universe-active'));return true}return false};if(!open()){let n=0;const wait=()=>{if(open())return;if(++n<40)setTimeout(wait,50)};setTimeout(wait,0)}return}if(isChart()&&a.dataset.page==='Terminal'&&document.body.classList.contains('universe-active')){e.preventDefault();document.body.classList.remove('universe-active');$('railUniverse')?.classList.remove('active');setActiveNav('Terminal');setPageLabel('Terminal');document.dispatchEvent(new Event('epinnox:chart-active'));return}setActiveNav(a.dataset.page);setPageLabel(a.dataset.page)}))}
  function setActiveNav(name){document.querySelectorAll('.ep-nav-item').forEach(a=>a.classList.toggle('active',a.dataset.page===name))}
  function setPageLabel(name){const el=$('epPageLabel');if(el)el.textContent=name||page();document.body.dataset.epPage=name||page()}
  function buildFooter(){const shell=document.querySelector(isChart()?'.app-shell':'.product-shell');if(!shell)return;document.querySelector('.statusbar')?.remove();document.querySelector('.status-bar')?.remove();document.querySelector('#pcFooter')?.remove();document.querySelector('#epGlobalFooter')?.remove();const f=document.createElement('footer');f.id='epGlobalFooter';f.className='ep-global-footer';f.innerHTML=`<div><i></i><b id="epClock">--:--:--</b><span id="epPageLabel">${esc(page())}</span></div><div id="epFooterTape" class="ep-footer-tape"></div><div class="ep-footer-cues"><span>◇ Evidence First</span><span>★ No Assumptions</span><span>Serve Benjamin ↗</span></div>`;shell.appendChild(f);tickClock();clockTimer=setInterval(tickClock,1000)}
  function tickClock(){if($('epClock'))$('epClock').textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'})}
  function buildProductMarketContext(){if(isChart())return;const layout=document.querySelector('.product-layout');if(!layout||document.querySelector('.ep-market-context'))return;const bar=document.createElement('section');bar.className='ep-market-context';bar.innerHTML=`<div>${assetIcon(selectedSymbol())}<span><b id="epContextSymbol">${esc(selectedSymbol())}</b><em>Canonical market context</em></span></div><a href="/">Open chart</a>`;layout.parentElement.insertBefore(bar,layout)}
  async function refreshMarket(){if(document.hidden)return;await Promise.allSettled(WATCH.map(async([symbol])=>{const d=await market(symbol),cl=(d.candles||[]).map(closeOf).filter(Number.isFinite);if(cl.length<2)return;const last=cl.at(-1),chg=cl[0]?((last/cl[0])-1)*100:0;document.querySelectorAll(`.ep-ticker[data-symbol="${CSS.escape(symbol)}"]`).forEach(card=>{const p=card.querySelector('[data-price]'),c=card.querySelector('[data-change]');if(p)p.textContent=fmt(last,last>=100?2:4);if(c){c.textContent=`${chg>=0?'+':''}${fmt(chg,2)}%`;c.classList.toggle('negative',chg<0)}})}));const tape=$('epFooterTape');if(tape)tape.innerHTML=WATCH.map(([,c])=>{const card=[...document.querySelectorAll('.ep-ticker')].find(x=>x.dataset.symbol.startsWith(`${c}/`)),change=card?.querySelector('[data-change]')?.textContent||'—';return `<span>${c} <b class="${change.startsWith('-')?'negative':''}">${esc(change)}</b></span>`}).join('')}
  async function refreshSessions(){if(isChart())return;try{const d=await fetch('/api/sessions?limit=20').then(r=>r.json()),active=(d.sessions||[]).filter(x=>ACTIVE_SESSION_STATES.has(String(x.status)));if($('epSessionCount'))$('epSessionCount').textContent=String(active.length);const box=$('epSessionList');if(box)box.innerHTML=active.length?active.slice(0,4).map((s,i)=>`<a href="/sessions" class="ep-session-row" data-state="${esc(s.status)}"><i></i><span><b>P-${String(i+1).padStart(2,'0')} · ${esc(code(s.symbol||s.request?.symbol))}</b><em>${esc(s.strategy||s.request?.strategy||'—')}</em></span></a>`).join(''):'<span>No active paper sessions.</span>'}catch{if($('epSessionList'))$('epSessionList').innerHTML='<span>Runtime unavailable.</span>'}}
  async function loadSymbols(){if(symbols)return symbols;try{const d=await fetch('/api/symbols').then(r=>r.json());symbols=Array.isArray(d.symbols)?d.symbols:[]}catch{symbols=WATCH.map(x=>x[0])}return symbols}
  async function renderSearch(){const box=$('epSearchResults'),q=($('epSymbolSearch')?.value||'').trim().toLowerCase();if(!box)return;if(!q){box.classList.add('hidden');box.innerHTML='';return}const rows=(await loadSymbols()).filter(s=>String(s).toLowerCase().includes(q)||code(s).toLowerCase().includes(q)).slice(0,9);box.innerHTML=rows.length?rows.map(s=>`<button type="button" data-symbol="${esc(s)}">${assetIcon(s)}<span><b>${esc(code(s))}</b><em>${esc(s)}</em></span></button>`).join(''):'<span class="ep-empty">No matching symbol</span>';box.classList.remove('hidden');box.querySelectorAll('[data-symbol]').forEach(b=>b.addEventListener('click',()=>setSymbol(b.dataset.symbol)))}
  function closePopovers(){$('epSearchResults')?.classList.add('hidden');$('epSystemPopover')?.classList.add('hidden')}
  async function showSystem(){const box=$('epSystemPopover');if(!box)return;box.classList.remove('hidden');box.innerHTML='<strong>SYSTEM STATUS</strong><span>Checking runtime…</span>';const led=$('epSystemLed');try{const s=await fetch('/api/live/status').then(r=>r.json());const bad=[s.universe?.state,s.scanner?.state].some(x=>['DEGRADED','ERROR','STOPPED'].includes(String(x||'')));if(led)led.classList.toggle('warn',bad);box.innerHTML=`<strong>SYSTEM STATUS</strong><span>Universe <b>${esc(s.universe?.state||'—')}</b></span><span>Scanner <b>${esc(s.scanner?.state||'—')}</b></span><span>Cycle <b>${esc(s.scanner?.cycle??'—')}</b></span>`}catch{if(led)led.classList.add('warn');box.innerHTML='<strong>SYSTEM STATUS</strong><span>Runtime unavailable.</span>'}}
  function boot(){buildHeader();buildSidebar();buildProductMarketContext();buildFooter();document.documentElement.classList.add('ep-canonical-shell');document.body.dataset.epPage=page();if(new URLSearchParams(location.search).has('universe')){setActiveNav('Universe');setPageLabel('Universe')}refreshMarket();refreshSessions();marketTimer=setInterval(refreshMarket,15000);sessionTimer=setInterval(()=>{if(!document.hidden)refreshSessions()},5000);document.addEventListener('epinnox:universe-active',()=>{setActiveNav('Universe');setPageLabel('Universe')});document.addEventListener('epinnox:chart-active',()=>{if(!document.body.classList.contains('universe-active')){setActiveNav('Terminal');setPageLabel('Terminal')}});document.addEventListener('visibilitychange',()=>{if(!document.hidden){refreshMarket();refreshSessions()}});window.addEventListener('beforeunload',()=>{clearInterval(marketTimer);clearInterval(sessionTimer);clearInterval(clockTimer)})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();