(()=>{
  if(window.__EPINNOX_PRODUCT_CHROME__)return;
  window.__EPINNOX_PRODUCT_CHROME__=true;
  const $=id=>document.getElementById(id);
  const WATCH=[
    {symbol:'BTC/USDT:USDT',code:'BTC',name:'Bitcoin'},
    {symbol:'ETH/USDT:USDT',code:'ETH',name:'Ethereum'},
    {symbol:'SOL/USDT:USDT',code:'SOL',name:'Solana'},
    {symbol:'XRP/USDT:USDT',code:'XRP',name:'XRP'},
  ];
  const marketCache=new Map();
  let clockTimer=null,marketTimer=null,sessionTimer=null,symbolsCache=null;
  const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const codeOf=s=>String(s||'').split('/')[0].replace(/[^A-Z0-9]/gi,'').toUpperCase()||'—';
  const fmt=(v,d=2)=>Number.isFinite(Number(v))?Number(v).toLocaleString(undefined,{minimumFractionDigits:d,maximumFractionDigits:d}):'—';

  function iconMarkup(symbol,size='sm'){
    const c=codeOf(symbol);
    if(c==='ETH')return `<span class="pc-asset-icon ${size} eth"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2 5.8 12.2 12 15.8l6.2-3.6L12 2Zm0 15.1-6.2-3.6L12 22l6.2-8.5-6.2 3.6Z"/></svg></span>`;
    if(c==='BTC')return `<span class="pc-asset-icon ${size} btc">₿</span>`;
    if(c==='SOL')return `<span class="pc-asset-icon ${size} sol"><i></i><i></i><i></i></span>`;
    if(c==='XRP')return `<span class="pc-asset-icon ${size} xrp"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 6c1.7 0 2.5.7 3.7 2l3.3 3.5L15.3 8C16.5 6.7 17.3 6 19 6h2l-5.8 6 5.8 6h-2c-1.7 0-2.5-.7-3.7-2L12 12.5 8.7 16C7.5 17.3 6.7 18 5 18H3l5.8-6L3 6h2Z"/></svg></span>`;
    return `<span class="pc-asset-icon ${size} generic">${esc(c.slice(0,2))}</span>`;
  }

  function sparkline(values,w=62,h=18){const pts=values.map(Number).filter(Number.isFinite);if(pts.length<2)return'';const lo=Math.min(...pts),hi=Math.max(...pts),r=hi-lo||1;const d=pts.map((v,i)=>`${i?'L':'M'}${(i/(pts.length-1)*w).toFixed(1)},${(h-2-((v-lo)/r)*(h-4)).toFixed(1)}`).join(' ');return `<svg class="pc-spark" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><path d="${d}"/></svg>`}
  async function fetchMarket(symbol,limit=100){const key=`${symbol}|${limit}`,hit=marketCache.get(key);if(hit&&Date.now()-hit.at<12000)return hit.data;const r=await fetch(`/api/market?symbol=${encodeURIComponent(symbol)}&timeframe=1m&limit=${limit}`);const d=await r.json();if(!r.ok)throw new Error(d.detail||'market unavailable');marketCache.set(key,{at:Date.now(),data:d});return d}

  function currentPage(){const p=location.pathname;return p.startsWith('/scanner')?'Scanner':p.startsWith('/sessions')?'Sessions':p.startsWith('/research')?'Research':p.startsWith('/strategies')?'Strategies':'Terminal'}
  function setWorkspaceSymbol(symbol){let w={schema_version:1,saved_at_ms:Date.now(),mode:'BACKTEST',values:{}};try{const x=JSON.parse(localStorage.getItem('epinnox.workspace.v1')||'null');if(x?.schema_version===1)w=x}catch{}w.saved_at_ms=Date.now();w.mode='BACKTEST';w.values={...(w.values||{}),symbol};localStorage.setItem('epinnox.workspace.v1',JSON.stringify(w));location.href='/'}

  function installHeader(){
    const header=document.querySelector('.product-header');if(!header)return;header.classList.add('pc-header');
    const health=header.querySelector('.product-health');if(health){health.id='pcTickerDeck';health.className='pc-ticker-deck';health.innerHTML=WATCH.map(x=>`<button type="button" class="pc-ticker" data-symbol="${x.symbol}" title="Open ${x.name}"><span class="pc-ticker-id">${iconMarkup(x.symbol,'xs')}<b>${x.code}</b></span><span class="pc-ticker-quote"><strong data-price>—</strong><em data-change>—</em></span><span data-spark class="pc-ticker-spark"></span></button>`).join('');health.querySelectorAll('[data-symbol]').forEach(b=>b.addEventListener('click',()=>setWorkspaceSymbol(b.dataset.symbol)))}
    const mode=header.querySelector('.product-mode');if(mode){mode.id='pcTopTools';mode.className='pc-top-tools';mode.innerHTML=`<div class="pc-search"><span>⌕</span><input id="pcSymbolSearch" type="search" autocomplete="off" placeholder="Search symbol…" aria-label="Search symbol"><div id="pcSearchResults" class="pc-popover pc-search-results hidden"></div></div><button id="pcAlerts" class="pc-icon-button" type="button" title="System status">◌<i></i></button><button id="pcSettings" class="pc-icon-button" type="button" title="Strategy configuration">⚙</button><button id="pcProfile" class="pc-profile" type="button"><span>E</span><b>Epinnox<em><i></i> Connected</em></b></button><div id="pcSystemPopover" class="pc-popover pc-system hidden"></div>`;
      $('pcSymbolSearch')?.addEventListener('input',renderSearch);$('pcSymbolSearch')?.addEventListener('keydown',e=>{if(e.key==='Escape')closePopovers();if(e.key==='Enter'){const first=$('pcSearchResults')?.querySelector('[data-symbol]');if(first)setWorkspaceSymbol(first.dataset.symbol)}});$('pcAlerts')?.addEventListener('click',e=>{e.stopPropagation();showSystem()});$('pcSettings')?.addEventListener('click',()=>location.href='/?open=strategy');$('pcProfile')?.addEventListener('click',e=>{e.stopPropagation();showProfile()});document.addEventListener('click',e=>{if(!e.target.closest?.('#pcTopTools'))closePopovers()});
    }
  }

  function installSidebar(){const side=document.querySelector('.product-sidebar');if(!side)return;const label=side.querySelector('.nav-label');if(label)label.textContent='COMMAND CENTER';const icons={Terminal:'⌁',Scanner:'⌘',Sessions:'▣',Research:'◇',Strategies:'◈'};side.querySelectorAll('.product-nav a').forEach(a=>{const text=a.querySelector('.nav-copy strong')?.textContent?.trim()||'';const i=a.querySelector('.nav-icon');if(i){i.textContent=icons[text]||'◇';i.classList.add('pc-nav-icon')}a.title=text});if(!side.querySelector('.pc-session-block')){const status=side.querySelector('.sidebar-status');const block=document.createElement('section');block.className='pc-session-block';block.innerHTML='<div class="pc-side-label"><span>PAPER SESSIONS</span><b id="pcSessionCount">0</b></div><div id="pcSessionMini" class="pc-session-mini"><span>Loading runtime…</span></div><a class="pc-new-session" href="/?mode=PAPER">＋ New Session</a>';side.insertBefore(block,status||null)}if(!side.querySelector('.pc-side-art')){const art=document.createElement('div');art.className='pc-side-art';art.innerHTML='<div></div><span>DISCIPLINE<br>BUILDS FREEDOM</span>';side.appendChild(art)}}

  function installFooter(){const shell=document.querySelector('.product-shell');if(!shell||$('pcFooter'))return;const footer=document.createElement('footer');footer.id='pcFooter';footer.className='pc-footer';footer.innerHTML=`<div class="pc-footer-clock"><i></i><b id="pcClock">--:--:--</b><span>${esc(currentPage())}</span></div><div id="pcFooterTape" class="pc-footer-tape"></div><div class="pc-footer-cues"><span>◇ Evidence First</span><span>★ No Assumptions</span><span>Serve Benjamin ↗</span></div>`;shell.appendChild(footer);tickClock();clockTimer=setInterval(tickClock,1000)}
  function tickClock(){const el=$('pcClock');if(el)el.textContent=new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'})}

  async function refreshMarket(){if(document.hidden)return;await Promise.allSettled(WATCH.map(async item=>{const d=await fetchMarket(item.symbol,100),cl=(d.candles||[]).map(c=>Number(c[4])).filter(Number.isFinite);if(cl.length<2)return;const first=cl[0],last=cl.at(-1),chg=first?((last/first)-1)*100:0;document.querySelectorAll(`.pc-ticker[data-symbol="${CSS.escape(item.symbol)}"]`).forEach(card=>{const p=card.querySelector('[data-price]'),c=card.querySelector('[data-change]'),s=card.querySelector('[data-spark]');if(p)p.textContent=fmt(last,last>=100?2:4);if(c){c.textContent=`${chg>=0?'+':''}${fmt(chg,2)}%`;c.classList.toggle('negative',chg<0)}if(s)s.innerHTML=sparkline(cl.slice(-48))});}));const tape=$('pcFooterTape');if(tape)tape.innerHTML=WATCH.map(item=>{const card=document.querySelector(`.pc-ticker[data-symbol="${CSS.escape(item.symbol)}"]`),change=card?.querySelector('[data-change]')?.textContent||'—';return `<span>${item.code} <b class="${change.startsWith('-')?'negative':''}">${esc(change)}</b></span>`}).join('')}

  async function loadSymbols(){if(symbolsCache)return symbolsCache;try{const d=await fetch('/api/symbols').then(r=>r.json());symbolsCache=Array.isArray(d.symbols)?d.symbols:[]}catch{symbolsCache=WATCH.map(x=>x.symbol)}return symbolsCache}
  async function renderSearch(){const box=$('pcSearchResults'),q=($('pcSymbolSearch')?.value||'').trim().toLowerCase();if(!box)return;if(!q){box.classList.add('hidden');box.innerHTML='';return}const symbols=await loadSymbols(),rows=symbols.filter(s=>String(s).toLowerCase().includes(q)||codeOf(s).toLowerCase().includes(q)).slice(0,9);box.innerHTML=rows.length?rows.map(s=>`<button type="button" data-symbol="${esc(s)}">${iconMarkup(s,'xs')}<span><b>${esc(codeOf(s))}</b><em>${esc(s)}</em></span></button>`).join(''):'<span class="pc-search-empty">No matching symbol</span>';box.classList.remove('hidden');box.querySelectorAll('[data-symbol]').forEach(b=>b.addEventListener('click',()=>setWorkspaceSymbol(b.dataset.symbol)))}
  function closePopovers(){$('pcSearchResults')?.classList.add('hidden');$('pcSystemPopover')?.classList.add('hidden')}
  async function showSystem(){const box=$('pcSystemPopover');if(!box)return;box.classList.remove('hidden');box.innerHTML='<div class="pc-pop-head">SYSTEM STATUS</div><div class="pc-system-row"><span>Runtime</span><b>Checking…</b></div>';try{const s=await fetch('/api/execution/status').then(r=>r.json());box.innerHTML=`<div class="pc-pop-head">SYSTEM STATUS</div><div class="pc-system-row"><span>Backtest</span><b>${esc(s.backtest||'—')}</b></div><div class="pc-system-row"><span>Scanner</span><b>${esc(s.scanner||'—')}</b></div><div class="pc-system-row"><span>Paper sessions</span><b>${esc(s.paper_sessions_active??0)} active</b></div><div class="pc-system-row warning"><span>Live routing</span><b>${esc(s.live_order_routing||'not armed')}</b></div>`}catch{box.innerHTML='<div class="pc-pop-head">SYSTEM STATUS</div><div class="pc-system-note">Runtime status unavailable.</div>'}}
  function showProfile(){const box=$('pcSystemPopover');if(!box)return;box.classList.remove('hidden');box.innerHTML=`<div class="pc-pop-head">EPINNOX</div><div class="pc-system-row"><span>Surface</span><b>${esc(currentPage())}</b></div><div class="pc-system-row"><span>Intelligence</span><b>Serving Benjamin</b></div><div class="pc-system-note">Evidence-first research and governed execution workspace.</div>`}

  async function refreshSessions(){try{const d=await fetch('/api/sessions?limit=20').then(r=>r.json()),active=(d.sessions||[]).filter(x=>['RUNNING','RECOVERED','RECONCILING','RECOVERY_REQUIRED'].includes(String(x.status)));if($('pcSessionCount'))$('pcSessionCount').textContent=String(active.length);const box=$('pcSessionMini');if(box)box.innerHTML=active.length?active.slice(0,4).map((s,i)=>{const req=s.request||{},symbol=s.symbol||req.symbol||'—',tf=s.timeframe||req.timeframe||'—',strategy=s.strategy||req.strategy||'—',status=String(s.status||'UNKNOWN');return `<a href="/sessions" class="pc-session-row" data-state="${esc(status)}"><i></i><span><b>P-${String(i+1).padStart(2,'0')} · ${esc(codeOf(symbol))} ${esc(tf)}</b><em>${esc(strategy)}</em></span><strong>${esc(status.replaceAll('_',' '))}</strong></a>`}).join(''):'<span>No active paper sessions.</span>'}catch{const box=$('pcSessionMini');if(box)box.innerHTML='<span>Runtime unavailable.</span>'}}

  function decorateScanner(){document.querySelectorAll('#scannerRows tr').forEach(row=>{const cell=row.children?.[2];if(!cell||cell.querySelector('.pc-inline-asset'))return;const symbol=cell.textContent.trim();if(!symbol.includes('/'))return;cell.innerHTML=`<span class="pc-inline-asset">${iconMarkup(symbol,'xs')}<b>${esc(codeOf(symbol))}</b><em>${esc(symbol)}</em></span>`})}
  function decorateSessions(){document.querySelectorAll('.session-row .session-cell').forEach(cell=>{const label=cell.querySelector('span')?.textContent?.trim();const b=cell.querySelector('b');if(label!=='Market'||!b||b.querySelector('.pc-inline-market'))return;const raw=b.textContent.trim(),symbol=raw.split(' · ')[0];b.innerHTML=`<span class="pc-inline-market">${iconMarkup(symbol,'xs')}${esc(raw)}</span>`})}
  function observeContent(){const root=document.querySelector('.product-main');if(!root)return;const run=()=>{decorateScanner();decorateSessions()};run();new MutationObserver(run).observe(root,{childList:true,subtree:true})}

  function boot(){installHeader();installSidebar();installFooter();observeContent();refreshMarket();refreshSessions();marketTimer=setInterval(refreshMarket,15000);sessionTimer=setInterval(()=>{if(!document.hidden)refreshSessions()},5000);document.addEventListener('visibilitychange',()=>{if(!document.hidden){refreshMarket();refreshSessions()}});window.addEventListener('beforeunload',()=>{clearInterval(clockTimer);clearInterval(marketTimer);clearInterval(sessionTimer)})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();