const $=id=>document.getElementById(id);
const STATE_KEY='epinnox.scanner.v2';
let config=null,lastScan=null;
const n=(v,d=2)=>v===null||v===undefined||Number.isNaN(Number(v))?'—':Number(v).toFixed(d);
const money=(v,d=2)=>v===null||v===undefined||Number.isNaN(Number(v))?'—':`$${Number(v).toLocaleString(undefined,{minimumFractionDigits:d,maximumFractionDigits:d})}`;
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const selected=id=>[...$(id).selectedOptions].map(o=>o.value);
const setSelected=(id,values)=>{const wanted=new Set(values||[]);[...$(id).options].forEach(o=>o.selected=wanted.has(o.value))};

function parseTargets(){return $('scanTargets').value.split(',').map(x=>Number(x.trim())).filter(x=>Number.isFinite(x)&&x>=0)}
function feeFloor(){const e=Number($('scanEntryFee').value)/100,x=Number($('scanExitFee').value)/100,c=Number($('scanExtraCost').value)/100;const long=((1+e+c)/(1-x)-1)*100;const short=(1-(1-e-c)/(1+x))*100;return{long,short}}
function updateDerived(){const symbols=selected('scanSymbols').length,tfs=selected('scanTimeframes').length,strategies=selected('scanStrategies').length,targets=parseTargets().length,windows=Number($('scanWindows').value)||0;const evals=symbols*tfs*strategies*targets;const simulations=evals*(2+windows);$('combinationCount').textContent=`${evals} candidates · ~${simulations} simulations`;const f=feeFloor();$('feeFloorPreview').textContent=`Modeled fee floor · Long ${n(f.long,4)}% · Short ${n(f.short,4)}%`;saveState()}
function objectiveHelp(){const throughput=$('scanObjective').value==='Break-Even Throughput';$('objectiveHelp').textContent=throughput?'Maximize qualified OOS trade throughput while requiring non-negative holdout trader economics.':'Prioritize holdout return, robustness, walk-forward stability and lower drawdown.';saveState()}

function snapshot(){return{schema_version:2,objective:$('scanObjective').value,symbols:selected('scanSymbols'),timeframes:selected('scanTimeframes'),strategies:selected('scanStrategies'),history_bars:Number($('scanBars').value),targets:$('scanTargets').value,windows:Number($('scanWindows').value),min_trades:Number($('scanMinTrades').value),pass_rate:Number($('scanPassRate').value),max_dd:Number($('scanMaxDd').value),min_expectancy:Number($('scanMinExpectancy').value),holdout:Number($('scanHoldout').value),min_holdout_trades:Number($('scanMinHoldoutTrades').value),min_holdout_expectancy:Number($('scanMinHoldoutExpectancy').value),balance:Number($('scanBalance').value),leverage:Number($('scanLeverage').value),allocation:Number($('scanAllocation').value),entry_fee:Number($('scanEntryFee').value),exit_fee:Number($('scanExitFee').value),extra_cost:Number($('scanExtraCost').value),referral:Number($('scanReferral').value),qualified_only:$('qualifiedOnly').checked}}
function saveState(){try{localStorage.setItem(STATE_KEY,JSON.stringify(snapshot()))}catch{}}
function restoreState(defaults){let s=null;try{s=JSON.parse(localStorage.getItem(STATE_KEY)||'null')}catch{};if(!s||s.schema_version!==2)s=null;const d=defaults||{};$('scanObjective').value=s?.objective||d.objective||'Capital Growth';setSelected('scanSymbols',s?.symbols||d.symbols||[]);setSelected('scanTimeframes',s?.timeframes||d.timeframes||[]);setSelected('scanStrategies',s?.strategies||d.strategies||[]);$('scanBars').value=s?.history_bars??d.history_bars??2000;$('scanTargets').value=s?.targets??(d.target_buffers_pct||[0,.005,.01,.02,.04,.08]).join(', ');$('scanWindows').value=s?.windows??d.walk_forward_windows??4;$('scanMinTrades').value=s?.min_trades??d.min_sample_trades??20;$('scanPassRate').value=s?.pass_rate??d.min_walk_forward_pass_rate_pct??60;$('scanMaxDd').value=s?.max_dd??d.max_drawdown_pct??5;$('scanMinExpectancy').value=s?.min_expectancy??d.min_net_expectancy_usdt??0;$('scanHoldout').value=s?.holdout??Number(d.holdout_fraction??.25)*100;$('scanMinHoldoutTrades').value=s?.min_holdout_trades??d.min_holdout_trades??5;$('scanMinHoldoutExpectancy').value=s?.min_holdout_expectancy??d.min_holdout_expectancy_usdt??0;$('qualifiedOnly').checked=s?.qualified_only??true;const account=config?.defaults?.account_defaults||{};const econ=config?.defaults?.economics_defaults||{};$('scanBalance').value=s?.balance??account.starting_balance??100000;$('scanLeverage').value=s?.leverage??account.leverage??1;$('scanAllocation').value=s?.allocation??account.allocation_pct??5;$('scanEntryFee').value=s?.entry_fee??econ.entry_fee_pct??.05;$('scanExitFee').value=s?.exit_fee??econ.exit_fee_pct??.05;$('scanExtraCost').value=s?.extra_cost??econ.extra_cost_pct??0;$('scanReferral').value=s?.referral??econ.referral_share_pct??30;objectiveHelp();updateDerived()}

function payload(){const targets=parseTargets();if(!targets.length)throw new Error('Enter at least one target buffer.');const symbols=selected('scanSymbols'),timeframes=selected('scanTimeframes'),strategies=selected('scanStrategies');if(!symbols.length||!timeframes.length||!strategies.length)throw new Error('Select at least one symbol, timeframe and strategy.');return{symbols,timeframes,strategies,objective:$('scanObjective').value,history_bars:Number($('scanBars').value),target_buffers_pct:targets,walk_forward_windows:Number($('scanWindows').value),min_sample_trades:Number($('scanMinTrades').value),min_walk_forward_pass_rate_pct:Number($('scanPassRate').value),max_drawdown_pct:Number($('scanMaxDd').value),min_net_expectancy_usdt:Number($('scanMinExpectancy').value),holdout_fraction:Number($('scanHoldout').value)/100,min_holdout_trades:Number($('scanMinHoldoutTrades').value),min_holdout_expectancy_usdt:Number($('scanMinHoldoutExpectancy').value),starting_balance:Number($('scanBalance').value),leverage:Number($('scanLeverage').value),allocation_pct:Number($('scanAllocation').value),pyramiding:1,direction:'Both',entry_fee_pct:Number($('scanEntryFee').value),exit_fee_pct:Number($('scanExitFee').value),extra_cost_pct:Number($('scanExtraCost').value),referral_share_pct:Number($('scanReferral').value),maintenance_margin_pct:Number(config?.defaults?.economics_defaults?.maintenance_margin_pct??.4),backtest_profile:'TradingView Parity'}}

function renderSummary(d){const f=d.fee_floor,s=d.summary;$('scanSummary').innerHTML=`<div class="metric"><span>Evaluated</span><b>${s.evaluated}</b></div><div class="metric"><span>Qualified</span><b>${s.qualified}</b></div><div class="metric"><span>Fee floor long</span><b>${n(f.long_pct,4)}%</b></div><div class="metric"><span>Fee floor short</span><b>${n(f.short_pct,4)}%</b></div>`;$('rankingPolicy').textContent=d.ranking_policy||'';const b=s.best_candidate;if(!b){$('bestCandidate').innerHTML='<span class="muted">No candidate passed the current full-sample, walk-forward and chronological holdout rules.</span>';return}const o=b.holdout||{};$('bestCandidate').innerHTML=`<div class="section-heading"><span class="eyebrow">TOP QUALIFIED CANDIDATE</span><span class="status-chip ok">QUALIFIED</span></div><b>${esc(b.symbol)} · ${esc(b.timeframe)} · ${esc(b.strategy)}</b><div class="best-grid"><div><span>Robustness</span><b>${n(b.robustness_score,1)}</b></div><div><span>OOS P&L</span><b class="${Number(o.net_pnl)>=0?'positive':'negative'}">${money(o.net_pnl)}</b></div><div><span>OOS expectancy</span><b>${money(o.net_expectancy_usdt,4)}</b></div><div><span>OOS trades/day</span><b>${n(o.trades_per_day,2)}</b></div><div><span>OOS PF</span><b>${n(o.profit_factor,2)}</b></div><div><span>WF pass</span><b>${n(b.walk_forward?.pass_rate_pct,1)}%</b></div><div><span>Full DD</span><b>${n(b.max_drawdown_pct,2)}%</b></div><div><span>Target buffer</span><b>${n(b.target_buffer_pct,4)}%</b></div></div><p class="muted compact-help">Validation: ${esc(d.validation_policy?.type||'holdout')} · Pine semantics ${esc(d.parity_semantics_version||'—')}</p>`}
function renderRows(){if(!lastScan)return;const only=$('qualifiedOnly').checked;const rows=lastScan.results.filter(r=>!only||r.qualified);$('scannerRows').innerHTML=rows.length?rows.map(r=>{const o=r.holdout||{};return `<tr class="${r.qualified?'qualified':'rejected'}" title="${esc((r.reject_reasons||[]).join(', '))}"><td>${r.qualified_rank??r.objective_rank}</td><td><span class="status-chip ${r.qualified?'ok':'no'}">${r.qualified?'QUALIFIED':'REJECTED'}</span></td><td>${esc(r.symbol)}</td><td>${esc(r.timeframe)}</td><td>${esc(r.strategy)}</td><td>${n(r.target_buffer_pct,4)}%</td><td>${n(r.robustness_score,1)}</td><td>${n(o.trades_per_day,2)}</td><td class="${Number(o.net_pnl)>=0?'positive':'negative'}">${money(o.net_pnl)}</td><td>${money(o.net_expectancy_usdt,4)}</td><td>${n(o.profit_factor,2)}</td><td>${n(r.walk_forward?.pass_rate_pct,1)}%</td><td>${n(r.max_drawdown_pct,2)}%</td><td class="${r.net_pnl>=0?'positive':'negative'}">${money(r.net_pnl)}</td><td>${money(o.referral_revenue_per_day,4)}</td><td><button class="load-candidate" data-rank="${r.objective_rank}">Load</button></td></tr>`}).join(''):'<tr><td colspan="16" class="empty-cell">No rows match this filter.</td></tr>';document.querySelectorAll('.load-candidate').forEach(b=>b.addEventListener('click',()=>loadCandidate(Number(b.dataset.rank))))}
function renderScan(d){lastScan=d;renderSummary(d);renderRows();const engine=d.engine_stats||{};$('scanStatus').textContent=`Complete · ${d.summary.evaluated} evaluated · ${d.summary.qualified} qualified · ${(d.duration_ms/1000).toFixed(1)}s · ${engine.strategy_builds_avoided??0} strategy rebuilds avoided`;refreshRuns()}

function loadCandidate(rank){const r=lastScan?.results.find(x=>x.objective_rank===rank);if(!r)return;let w={schema_version:1,saved_at_ms:Date.now(),mode:'BACKTEST',values:{}};try{const existing=JSON.parse(localStorage.getItem('epinnox.workspace.v1')||'null');if(existing?.schema_version===1)w=existing}catch{};w.saved_at_ms=Date.now();w.mode='BACKTEST';w.values={...(w.values||{}),symbol:r.symbol,timeframe:r.timeframe,strategy:r.strategy,backtestProfile:r.load_payload.backtest_profile||'TradingView Parity',balance:String(r.load_payload.starting_balance),leverage:String(r.load_payload.leverage),allocation:String(r.load_payload.allocation_pct),pyramiding:String(r.load_payload.pyramiding),direction:r.load_payload.direction,entryFee:String(r.load_payload.entry_fee_pct),exitFee:String(r.load_payload.exit_fee_pct),extraCost:String(r.load_payload.extra_cost_pct),netTarget:String(r.target_buffer_pct),referral:String(r.load_payload.referral_share_pct),maintenance:String(r.load_payload.maintenance_margin_pct),bars:String(r.load_payload.limit),maxBars:r.load_payload.max_bars_in_trade==null?'':String(r.load_payload.max_bars_in_trade),stopLoss:r.load_payload.stop_loss_pct==null?'':String(r.load_payload.stop_loss_pct),confirmationPolicy:'Single',confirm1:'',confirm2:''};localStorage.setItem('epinnox.workspace.v1',JSON.stringify(w));location.href='/'}

async function runScan(){let body;try{body=payload()}catch(e){$('scanStatus').textContent=e.message;return}saveState();$('runScan').disabled=true;$('scanStatus').classList.add('scanner-loading');$('scanStatus').textContent='Building Pine-parity strategy models, sweeping targets, walk-forward calibration and chronological holdout…';try{const r=await fetch('/api/scanner/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Scan failed');renderScan(d)}catch(e){$('scanStatus').textContent=`Scan error · ${e.message}`}finally{$('runScan').disabled=false;$('scanStatus').classList.remove('scanner-loading')}}
async function refreshRuns(){try{const d=await fetch('/api/scanner/runs?limit=8').then(r=>r.json());$('recentRuns').innerHTML=(d.runs||[]).length?d.runs.map(x=>`<div class="recent-run"><span>${new Date(x.completed_at_ms).toLocaleString()}</span><b>${esc(x.objective)}</b><span>${x.summary.evaluated} evaluated · ${x.summary.qualified} qualified</span><button class="chart-tool recent-load" data-id="${esc(x.scan_id)}">Open</button></div>`).join(''):'<span class="muted">No persisted scans yet.</span>';document.querySelectorAll('.recent-load').forEach(b=>b.addEventListener('click',async()=>{const r=await fetch(`/api/scanner/runs/${encodeURIComponent(b.dataset.id)}`);const d=await r.json();if(r.ok)renderScan(d)}))}catch(e){$('recentRuns').innerHTML=`<span class="scanner-error">${esc(e.message)}</span>`}}

async function boot(){config=await fetch('/api/config').then(r=>r.json());const sym=await fetch('/api/symbols').then(r=>r.json()).catch(()=>({symbols:['ETH/USDT:USDT','BTC/USDT:USDT','SOL/USDT:USDT']}));$('scanSymbols').innerHTML=sym.symbols.map(x=>`<option>${esc(x)}</option>`).join('');$('scanTimeframes').innerHTML=(config.timeframes||['1m','5m','15m','30m']).filter(x=>['1m','5m','15m','30m'].includes(x)).map(x=>`<option>${esc(x)}</option>`).join('');$('scanStrategies').innerHTML=(config.strategies||[]).map(x=>`<option>${esc(x)}</option>`).join('');restoreState(config.defaults?.scanner_defaults||{});['scanSymbols','scanTimeframes','scanStrategies','scanBars','scanTargets','scanWindows','scanMinTrades','scanPassRate','scanMaxDd','scanMinExpectancy','scanHoldout','scanMinHoldoutTrades','scanMinHoldoutExpectancy','scanBalance','scanLeverage','scanAllocation','scanEntryFee','scanExitFee','scanExtraCost','scanReferral'].forEach(id=>$(id).addEventListener('input',updateDerived));$('scanObjective').addEventListener('change',objectiveHelp);$('qualifiedOnly').addEventListener('change',()=>{saveState();renderRows()});$('runScan').addEventListener('click',runScan);$('refreshRuns').addEventListener('click',refreshRuns);await refreshRuns()}

boot().catch(e=>{$('scanStatus').textContent=`Boot error · ${e.message}`});