const $=id=>document.getElementById(id);
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const num=(v,d=2)=>v===null||v===undefined||!Number.isFinite(Number(v))?'—':Number(v).toFixed(d);
const money=v=>v===null||v===undefined||!Number.isFinite(Number(v))?'—':`$${Number(v).toLocaleString(undefined,{maximumFractionDigits:2})}`;
const age=ms=>{if(!ms)return'—';const s=Math.max(0,Math.floor((Date.now()-ms)/1000));if(s<60)return`${s}s`;if(s<3600)return`${Math.floor(s/60)}m`;return`${Math.floor(s/3600)}h`};
const selected=id=>[...$(id).selectedOptions].map(o=>o.value);
const setSelected=(id,values)=>{const wanted=new Set(values||[]);[...$(id).options].forEach(o=>o.selected=wanted.has(o.value))};
let config=null,status=null,universe=null,timer=null,refreshing=false,editing=false,draft=null;

const FIELDS=['scanObjective','scanTimeframes','scanStrategies','scanBars','scanTargets','scanWindows','scanMinTrades','scanPassRate','scanMaxDd','scanHoldout','scanMinHoldoutTrades','scanMinHoldoutExpectancy','scanBalance','scanLeverage','scanAllocation','scanBatch','scanEntryFee','scanExitFee','scanExtraCost','scanStale'];
function enableFields(on){FIELDS.forEach(id=>{if($(id))$(id).disabled=!on});}
function hydrateMandate(m){if(!m)return;$('scanObjective').value=m.objective||'Capital Growth';setSelected('scanTimeframes',m.timeframes||[]);setSelected('scanStrategies',m.strategies||[]);$('scanBars').value=m.history_bars??2000;$('scanTargets').value=(m.target_buffers_pct||[]).join(', ');$('scanWindows').value=m.walk_forward_windows??4;$('scanMinTrades').value=m.min_sample_trades??20;$('scanPassRate').value=m.min_walk_forward_pass_rate_pct??60;$('scanMaxDd').value=m.max_drawdown_pct??5;$('scanHoldout').value=Number(m.holdout_fraction??.25)*100;$('scanMinHoldoutTrades').value=m.min_holdout_trades??5;$('scanMinHoldoutExpectancy').value=m.min_holdout_expectancy_usdt??0;$('scanBalance').value=m.starting_balance??100000;$('scanLeverage').value=m.leverage??1;$('scanAllocation').value=m.allocation_pct??5;$('scanBatch').value=m.batch_size??2;$('scanEntryFee').value=m.entry_fee_pct??.05;$('scanExitFee').value=m.exit_fee_pct??.05;$('scanExtraCost').value=m.extra_cost_pct??0;$('scanStale').value=m.evidence_stale_seconds??14400;objectiveHelp();}
function objectiveHelp(){$('objectiveHelp').textContent=$('scanObjective').value==='Break-Even Throughput'?'Maximize qualified OOS trade throughput while preserving non-negative holdout economics.':'Prioritize holdout return, robustness, walk-forward stability and controlled drawdown.'}
function parseTargets(){return $('scanTargets').value.split(',').map(x=>Number(x.trim())).filter(x=>Number.isFinite(x)&&x>=0)}
function mandatePayload(){const targets=parseTargets(),tfs=selected('scanTimeframes'),strategies=selected('scanStrategies');if(!targets.length||!tfs.length||!strategies.length)throw new Error('Mandate requires at least one timeframe, strategy and target.');return{objective:$('scanObjective').value,timeframes:tfs,strategies,history_bars:Number($('scanBars').value),target_buffers_pct:targets,walk_forward_windows:Number($('scanWindows').value),min_sample_trades:Number($('scanMinTrades').value),min_walk_forward_pass_rate_pct:Number($('scanPassRate').value),max_drawdown_pct:Number($('scanMaxDd').value),holdout_fraction:Number($('scanHoldout').value)/100,min_holdout_trades:Number($('scanMinHoldoutTrades').value),min_holdout_expectancy_usdt:Number($('scanMinHoldoutExpectancy').value),starting_balance:Number($('scanBalance').value),leverage:Number($('scanLeverage').value),allocation_pct:Number($('scanAllocation').value),batch_size:Number($('scanBatch').value),entry_fee_pct:Number($('scanEntryFee').value),exit_fee_pct:Number($('scanExitFee').value),extra_cost_pct:Number($('scanExtraCost').value),evidence_stale_seconds:Number($('scanStale').value)}}
function beginEdit(){editing=true;draft=JSON.stringify(status?.mandate||{});enableFields(true);$('editMandate').hidden=true;$('cancelMandate').hidden=false;$('applyMandate').hidden=false;$('mandateState').textContent='STAGED · not yet active';$('mandateReview').textContent='Review changes before applying. The running batch keeps its admitted mandate.';}
function cancelEdit(){editing=false;enableFields(false);hydrateMandate(status?.mandate||{});$('editMandate').hidden=false;$('cancelMandate').hidden=true;$('applyMandate').hidden=true;$('mandateState').textContent='Runtime policy';$('mandateReview').textContent='Mandate is live. Edit to stage changes; Apply commits them for the next admitted batch.';}
async function applyMandate(){let body;try{body=mandatePayload()}catch(e){message(e.message,'error');return}$('applyMandate').disabled=true;try{const r=await fetch('/api/live/mandate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw new Error(d.detail||'Mandate rejected');status=d;editing=false;enableFields(false);hydrateMandate(d.mandate);$('editMandate').hidden=false;$('cancelMandate').hidden=true;$('applyMandate').hidden=true;message('Mandate accepted · takes effect on next admitted batch.','ok');render()}catch(e){message(e.message,'error')}finally{$('applyMandate').disabled=false}}
function message(text,kind=''){$('runtimeMessage').textContent=text;$('runtimeMessage').className=`runtime-message ${kind}`}

async function setControl(body){try{const r=await fetch('/api/live/control',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw new Error(d.detail||'Runtime control failed');status=d;render();await refresh(true)}catch(e){message(e.message,'error')}}
async function refresh(force=false){if(refreshing||document.hidden)return;refreshing=true;try{const [sr,ur]=await Promise.all([fetch('/api/live/status',{cache:'no-store'}),fetch('/api/live/universe?window=8h',{cache:'no-store'})]);const [s,u]=await Promise.all([sr.json(),ur.json()]);if(!sr.ok)throw new Error(s.detail||`Status ${sr.status}`);if(!ur.ok)throw new Error(u.detail||`Universe ${ur.status}`);status=s;universe=u;if(!editing)hydrateMandate(s.mandate);render();message('Continuous runtime connected · evidence refreshes automatically.','ok')}catch(e){message(`DEGRADED · ${e.message}`,'error');setBadge('DEGRADED')}finally{refreshing=false}}
function setBadge(state){const b=$('liveScannerBadge');b.innerHTML=`<i></i> ${esc(state)}`;b.dataset.state=state;$('scannerHeaderState').textContent=state;$('scannerHeaderState').classList.toggle('live',state==='RUNNING'||state==='IDLE')}
function render(){if(!status)return;const sc=status.scanner||{},uv=status.universe||{},controls=status.controls||{},assets=universe?.assets||[];const covered=assets.filter(x=>x.coverage_state==='COVERED').length,unscanned=assets.filter(x=>x.coverage_state==='UNSCANNED').length,stale=assets.filter(x=>x.coverage_state==='STALE').length;setBadge(sc.state||'—');$('scannerLiveToggle').checked=!!controls.scanner_enabled;$('universeLiveToggle').checked=!!controls.universe_enabled;$('pauseAll').textContent=!controls.scanner_enabled&&!controls.universe_enabled?'Resume all':'Pause all';$('rtState').textContent=sc.state||'—';$('rtCycle').textContent=sc.cycle??'—';$('rtBatch').textContent=(sc.active_batch||[]).map(x=>x.split('/')[0]).join(' · ')||'—';$('rtMarkets').textContent=uv.markets??assets.length;$('rtCovered').textContent=covered;$('rtUnscanned').textContent=unscanned;$('rtStale').textContent=stale;$('rtCommit').textContent=age(sc.last_commit_ms);$('scannerHeaderHealth').textContent=`Universe ${uv.state||'—'} · Scanner ${sc.state||'—'}`;renderOperations(assets);renderRows(assets);renderEvents();}
function renderOperations(assets){const sc=status.scanner||{},uv=status.universe||{},flow=uv.flow||{};const partial=assets.filter(x=>x.coverage_state==='PARTIAL').length,qualified=assets.filter(x=>x.qualification_state==='QUALIFIED').length;const items=[['Scanner',sc.state],['Universe',uv.state],['Cycle',sc.cycle],['Evidence rows',sc.evidence_rows],['Active batch',(sc.active_batch||[]).map(x=>x.split('/')[0]).join(' · ')||'—'],['Qualified assets',qualified],['Partial assets',partial],['Flow quality',flow.quality||'—'],['Last market tick',age(uv.last_tick_ms)],['Last evidence',age(sc.last_commit_ms)],['Scanner error',sc.error||'None'],['Universe error',uv.error||'None']];$('operations').innerHTML=items.map(([k,v])=>`<div><span>${esc(k)}</span><b>${esc(v??'—')}</b></div>`).join('')}
function candidateFromAsset(a){const b=a.best;if(!b)return null;const h=b.holdout||{};return{asset:a,raw:b,qualified:a.qualification_state==='QUALIFIED',symbol:a.symbol||b.symbol,timeframe:b.timeframe,strategy:b.strategy,target:b.target_buffer_pct,robust:b.robustness_score,trades:h.trades_per_day,pnl:h.net_pnl,expectancy:h.net_expectancy_usdt,pf:h.profit_factor,wf:b.walk_forward?.pass_rate_pct,dd:b.max_drawdown_pct,coverage:a.coverage_pct,updated:a.latest_evidence_ms,score:a.scanner_score}}
function renderRows(assets){let rows=assets.map(candidateFromAsset).filter(Boolean);if($('qualifiedOnly').checked)rows=rows.filter(x=>x.qualified);rows.sort((a,b)=>(b.qualified-a.qualified)||(Number(b.score||0)-Number(a.score||0)));$('scannerRows').innerHTML=rows.length?rows.map((r,i)=>`<tr class="${r.qualified?'qualified':'rejected'}"><td>${i+1}</td><td><span class="status-chip ${r.qualified?'ok':'no'}">${r.qualified?'QUALIFIED':esc(r.asset.coverage_state||'REJECTED')}</span></td><td>${esc(r.symbol)}</td><td>${esc(r.timeframe||'—')}</td><td>${esc(r.strategy||'—')}</td><td>${num(r.target,4)}%</td><td>${num(r.robust,1)}</td><td>${num(r.trades,2)}</td><td>${money(r.pnl)}</td><td>${money(r.expectancy)}</td><td>${num(r.pf,2)}</td><td>${num(r.wf,1)}%</td><td>${num(r.dd,2)}%</td><td>${num(r.coverage,0)}%</td><td>${age(r.updated)}</td><td><button class="load-candidate" data-symbol="${esc(r.asset.canonical_symbol)}">Inspect</button></td></tr>`).join(''):'<tr><td colspan="16" class="empty-cell">No candidates match this evidence filter yet. The live scanner continues working.</td></tr>';document.querySelectorAll('.load-candidate').forEach(b=>b.onclick=()=>{location.href=`/?universe=${encodeURIComponent(b.dataset.symbol)}`});renderBest(rows.find(x=>x.qualified)||rows[0])}
function renderBest(r){if(!r){$('bestCandidate').innerHTML='<span class="muted">No evidence committed yet.</span>';return}$('bestCandidate').innerHTML=`<div class="section-heading"><span class="eyebrow">${r.qualified?'TOP QUALIFIED':'BEST AVAILABLE EVIDENCE'}</span><span class="status-chip ${r.qualified?'ok':'no'}">${r.qualified?'QUALIFIED':esc(r.asset.coverage_state)}</span></div><b>${esc(r.symbol)} · ${esc(r.timeframe||'—')} · ${esc(r.strategy||'—')}</b><div class="best-grid"><div><span>Scanner score</span><b>${num(r.score,1)}</b></div><div><span>Robustness</span><b>${num(r.robust,1)}</b></div><div><span>OOS P&amp;L</span><b>${money(r.pnl)}</b></div><div><span>OOS expectancy</span><b>${money(r.expectancy)}</b></div><div><span>OOS PF</span><b>${num(r.pf,2)}</b></div><div><span>Coverage</span><b>${num(r.coverage,0)}%</b></div></div>`}
function renderEvents(){const ev=status.events||[];$('runtimeEvents').innerHTML=ev.length?ev.slice(0,12).map(x=>`<div class="runtime-event"><span>${new Date(x.ts_ms).toLocaleTimeString()}</span><b>${esc(String(x.kind||'event').replaceAll('_',' '))}</b><small>${esc(x.message||'')}</small></div>`).join(''):'<span class="muted">No runtime events yet.</span>'}

async function boot(){config=await fetch('/api/config').then(r=>r.json());$('scanTimeframes').innerHTML=(config.timeframes||['1m','5m','15m','30m']).filter(x=>['1m','5m','15m','30m'].includes(x)).map(x=>`<option>${esc(x)}</option>`).join('');$('scanStrategies').innerHTML=(config.strategies||[]).map(x=>`<option>${esc(x)}</option>`).join('');enableFields(false);$('editMandate').onclick=beginEdit;$('cancelMandate').onclick=cancelEdit;$('applyMandate').onclick=applyMandate;$('scanObjective').onchange=objectiveHelp;$('qualifiedOnly').onchange=()=>renderRows(universe?.assets||[]);$('scannerLiveToggle').onchange=e=>setControl({scanner_enabled:e.target.checked});$('universeLiveToggle').onchange=e=>setControl({universe_enabled:e.target.checked});$('pauseAll').onclick=()=>setControl({pause_all:!(!status?.controls?.scanner_enabled&&!status?.controls?.universe_enabled)});document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh(true)});await refresh(true);timer=setInterval(()=>refresh(false),2000);window.addEventListener('beforeunload',()=>clearInterval(timer));}
boot().catch(e=>message(`Boot error · ${e.message}`,'error'));