const $=id=>document.getElementById(id);
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const activeStates=new Set(['RUNNING','RECOVERED','RECONCILING','RECOVERY_REQUIRED']);
let rows=[],selectedId='';

function fmtTime(ms){if(!ms)return '—';try{return new Date(ms).toLocaleString()}catch{return '—'}}
function shortId(id){return String(id||'').slice(0,8).toUpperCase()||'—'}
function statusClass(status){status=String(status||'UNKNOWN');if(status==='RUNNING'||status==='RECOVERED')return'running';if(status==='RECOVERY_REQUIRED'||status==='RECONCILING')return'warning';if(status==='ERROR')return'error';return''}
function strategyLabel(s){const r=s.request||{};return s.name||`${s.symbol||r.symbol||'—'} · ${s.timeframe||r.timeframe||'—'} · ${s.strategy||r.strategy||'—'}`}

async function loadStatus(){try{const d=await fetch('/api/execution/status').then(r=>r.json());$('runtimeHealth').textContent=d.paper==='ready'?'Paper runtime ready':'Paper runtime not configured';$('kpiAuthority').textContent=d.epinnox_online_base_url?'ONLINE':'OFFLINE'}catch{$('runtimeHealth').textContent='Runtime status unavailable';$('kpiAuthority').textContent='—'}}

function applyFilter(){const f=$('sessionFilter').value;return rows.filter(s=>f==='ALL'||(f==='ACTIVE'&&activeStates.has(String(s.status)))||String(s.status)===f)}
function renderKpis(){const active=rows.filter(s=>activeStates.has(String(s.status))).length,running=rows.filter(s=>s.running||String(s.status)==='RUNNING').length,recovery=rows.filter(s=>String(s.status)==='RECOVERY_REQUIRED').length;$('kpiActive').textContent=active;$('kpiRunning').textContent=running;$('kpiRecovery').textContent=recovery;$('sessionRegistryMeta').textContent=`${rows.length} durable session${rows.length===1?'':'s'}`}
function renderRows(){const visible=applyFilter();if(!visible.length){$('sessionRows').innerHTML='<div class="session-empty"><strong>No sessions match this view</strong><span>Start a paper strategy from the Terminal or change the state filter.</span></div>';return}$('sessionRows').innerHTML=visible.map(s=>{const status=String(s.status||'UNKNOWN'),req=s.request||{};return `<button class="session-row ${selectedId===s.session_id?'active':''}" data-session-id="${esc(s.session_id)}"><span class="status-dot ${statusClass(status)}"></span><span class="row-main"><strong>${esc(strategyLabel(s))}</strong><span>${esc(shortId(s.session_id))} · ${esc(status.replaceAll('_',' '))}</span></span><span class="session-cell"><span>Market</span><b>${esc(s.symbol||req.symbol||'—')} · ${esc(s.timeframe||req.timeframe||'—')}</b></span><span class="session-cell"><span>Account</span><b class="mono">${esc(shortId(s.account_id))}</b></span><span class="session-cell"><span>Last bar</span><b class="session-time">${esc(fmtTime(s.last_bar_ts_ms))}</b></span><span class="status-chip ${statusClass(status)}">${esc(status.replaceAll('_',' '))}</span></button>`}).join('');document.querySelectorAll('.session-row').forEach(b=>b.addEventListener('click',()=>selectSession(b.dataset.sessionId)))}

function kv(label,value){return `<div class="detail-card"><span>${esc(label)}</span><b>${esc(value??'—')}</b></div>`}
function positionHtml(p){if(!p)return '<div class="position-box">No authoritative position snapshot is stored for this session.</div>';const parts=[];for(const k of ['side','qty','entry_price','avg_entry','unrealized_pnl','mark_price'])if(p[k]!==undefined&&p[k]!==null)parts.push(`<b>${esc(k.replaceAll('_',' '))}</b> ${esc(p[k])}`);return `<div class="position-box">${parts.length?parts.join('<br>'):esc(JSON.stringify(p))}</div>`}
function signalHtml(s){if(!s)return '<div class="signal-box">No qualifying signal has been checkpointed yet.</div>';const receipt=Array.isArray(s.receipt)?s.receipt.map(x=>`${x.matched?'✓':'×'} ${x.strategy}`).join(' · '):'';return `<div class="signal-box"><b>${esc(String(s.side||'signal').toUpperCase())}</b>${s.ts_ms?` · ${esc(fmtTime(s.ts_ms))}`:''}${receipt?`<br>${esc(receipt)}`:''}</div>`}
function eventsHtml(events){if(!Array.isArray(events)||!events.length)return '<div class="compact-note">No event receipts are available in the current snapshot.</div>';return `<div class="event-list">${events.slice().reverse().map(e=>`<div class="event-row"><time>${esc(new Date(e.ts_ms).toLocaleTimeString())}</time><b>${esc(e.kind||'event')}</b><span>${esc(e.detail||'')}</span></div>`).join('')}</div>`}

function renderDetail(s){if(!s){$('detailSessionId').textContent='select a session';$('sessionDetail').innerHTML='<div class="empty-state"><div><strong>No session selected</strong><p>Select a runtime to inspect ownership, strategy context, signal state, position and event receipts.</p></div></div>';return}const status=String(s.status||'UNKNOWN'),req=s.request||{},model=s.entry_model||{};$('detailSessionId').textContent=shortId(s.session_id);$('sessionDetail').innerHTML=`<div class="detail-hero"><div class="detail-meta"><span class="status-chip ${statusClass(status)}">${esc(status.replaceAll('_',' '))}</span><span class="product-badge">PAPER</span>${s.running?'<span class="product-badge live">runner active</span>':''}</div><h2>${esc(strategyLabel(s))}</h2><div class="compact-note">Bound ownership: account <span class="mono">${esc(s.account_id||'—')}</span> · instrument ${esc(s.symbol||req.symbol||'—')}.</div></div><div class="detail-grid">${kv('Strategy',s.strategy||req.strategy)}${kv('Timeframe',s.timeframe||req.timeframe)}${kv('Policy',model.policy||req.confirmation_policy||'Single')}${kv('Layers',s.layers??0)}${kv('Started',fmtTime(s.started_at_ms))}${kv('Last bar',fmtTime(s.last_bar_ts_ms))}${kv('Recovered',s.recovered_count??0)}${kv('Bars in position',s.bars_in_position??0)}</div><section class="detail-section"><div class="detail-section-head"><strong>POSITION</strong><span>checkpoint</span></div>${positionHtml(s.position)}</section><section class="detail-section"><div class="detail-section-head"><strong>LATEST SIGNAL</strong><span>evidence</span></div>${signalHtml(s.last_signal)}</section>${s.pending_intent?`<section class="detail-section"><div class="detail-section-head"><strong>PENDING INTENT</strong><span>fail-closed</span></div><div class="signal-box mono">${esc(JSON.stringify(s.pending_intent))}</div></section>`:''}${s.last_error?`<section class="detail-section"><div class="detail-section-head"><strong>LAST ERROR</strong></div><div class="error-box">${esc(s.last_error)}</div></section>`:''}<section class="detail-section"><div class="detail-section-head"><strong>EVENT RECEIPTS</strong><span>${Array.isArray(s.events)?s.events.length:0} shown</span></div>${eventsHtml(s.events)}</section><div class="detail-actions">${s.recoverable||activeStates.has(status)?'<button id="recoverSession" class="ep-btn primary">Recover / reconcile</button>':''}${status!=='STOPPED'?'<button id="stopSession" class="ep-btn danger">Stop runtime</button>':''}</div>`;$('recoverSession')?.addEventListener('click',()=>mutateSession('recover'));$('stopSession')?.addEventListener('click',()=>mutateSession('stop'))}

async function selectSession(id){selectedId=id;renderRows();$('detailSessionId').textContent='loading…';try{const r=await fetch(`/api/sessions/${encodeURIComponent(id)}`),d=await r.json();if(!r.ok)throw new Error(d.detail||'Session load failed');renderDetail(d)}catch(e){$('sessionDetail').innerHTML=`<div class="error-box">${esc(e.message)}</div>`}}
async function mutateSession(action){if(!selectedId)return;const btn=action==='stop'?$('stopSession'):$('recoverSession');if(btn)btn.disabled=true;try{const r=await fetch(`/api/sessions/${encodeURIComponent(selectedId)}/${action}`,{method:'POST'}),d=await r.json();if(!r.ok)throw new Error(d.detail||`${action} failed`);await refresh();await selectSession(selectedId);document.dispatchEvent(new CustomEvent('epinnox:session-mutated'))}catch(e){alert(`${action} failed: ${e.message}`)}finally{if(btn)btn.disabled=false}}

async function refresh(){await loadStatus();try{const r=await fetch('/api/sessions?limit=250'),d=await r.json();if(!r.ok)throw new Error(d.detail||'Session registry unavailable');rows=Array.isArray(d.sessions)?d.sessions:[];renderKpis();renderRows();if(selectedId&&!rows.some(x=>x.session_id===selectedId)){selectedId='';renderDetail(null)}}catch(e){$('sessionRows').innerHTML=`<div class="session-empty"><strong>Session registry unavailable</strong><span>${esc(e.message)}</span></div>`}}

$('refreshSessions').addEventListener('click',refresh);$('sessionFilter').addEventListener('change',renderRows);refresh();setInterval(()=>{if(!document.hidden)refresh()},5000);